### ISSUE TITLE
Archive refactor to facilitate accurate balance tracking

### ISSUE THREAD

**Issue by jlopker** [cobudget/cobudget#123]

**Comment by jessykate** [comment]
comments here: https://github.com/cobudget/cobudget-ui/pull/343

**Comment by chime-mu** [comment]
As far as I understand, the _why_ is so that you can mark previously archived buckets as paid. Is that correct?

And the _who_ is probably not any user, but either the group admin or the original bucket-proposer, as those are the only ones who can archive.

**Comment by jessykate** [comment]
summary of discussion on this today and our thinking, just for our reference:

our goal is to enable admins to manage the balance of a group, which means offering the ability to mark buckets as paid. we have deployed this feature already. the current state of the app allows for (and has) archived buckets that are also funded. so we need a way to get these funded, archived buckets to a paid state. 

we also need the ability to "cancel" a bucket (return the funds), which is currently possible with partially funded buckets but _not_ with fully funded buckets. examples of reasons why you might want to cancel a fully funded bucket: the funding was too late, the proposer doesn't have time or interest anymore, the thing you wanted to buy was bought by someone else, other external circumstances changed. 

the initial thinking was that it seems weird to allow state changes on archived buckets, so we should allow un-archiving of buckets and then admins can do whatever actions they need (mark as paid, cancel it). 

so this would mean you can un-archive a bucket, and then either mark it as paid, or cancelled (cancelled will return the funds). to do this, either we make a new state called cancelled, in which case the archived state becomes kind of useless (what does it mean to be archived if it doesn't mean cancelled or paid?). or, we _use_ the archived state as cancelled-- in which case it becomes contradictory to be able to un-archive buckets, because they were cancelled (funds returned)! un-archiving a cancelled bucket could not reclaim the returned funds (since they may have already been spent elsewhere, and also it would be a dick move), so the only meaningful way to un-archive a cancelled bucket is to put it back into idea phase and allow it to start accepting funds from scratch again (which is a new feature).

so we went through two possible approaches which are pretty similar but subtly different. the TL;DR is we propose to:

* introduce a new status, `refunded`
* enable 2 new actions on archived && funded buckets: mark as paid, and return funds. 
* update the archive action on funded and _not_ archived buckets to return funds. this means that for any future buckets that were not already archived, they will either be archived with funds returned, OR marked as paid. but these statuses will become mutually exclusive.   
* update the logic on displaying funded buckets, to include all funded and paid buckets, even if they were previously marked as archived. the paid section can be displayed as default-collapsed, to address the monotonically increasing size. 

this will let us address the currently funded and archived buckets without introducing an un-archive function directly. it is a bit weird to allow actions on archived buckets BUT the above scheme will result over time, in archived buckets converging on _only_ being cancelled buckets, and funded + paid buckets will never get archived but will simply be marked as paid.  

Discussion:
![img_4308_discussion](https://cloud.githubusercontent.com/assets/59882/24683096/ff1d0e86-1951-11e7-80a2-82ce011e0b70.JPG)

Rough Plan:
![img_6813_roughplan](https://cloud.githubusercontent.com/assets/59882/24683104/05a3f4d6-1952-11e7-83ee-9debfde9e97b.JPG)

**Comment by chime-mu** [comment]
Love the work and given I understand this correctly I think the conceptual solution makes a lot of sense. 

So let med play back what I understand.

## Conceptual states
* *Draft*
* *Live* (unfunded)
* *Partially funded*
* *Fully funded*
* *Cancelled* (terminal state)
* *Paid out* (terminal state)
* *Cancelled or Paid out* (previously known as *archived*. Only exists historically. New buckets can’t end up in this state. From here an admin can move to *Paid out* or *Cancelled*)

## Implementation of states
*Draft* - `status=draft`
*Live* - `status=live`, `live_at` has a date
*Partially funded* - ???
*Fully funded* - ???
*Cancelled* - `status=refunded`, ???
*Paid out* - `status=funded`, `live_at`+f`unded_at`+`paid_at` has  dates
*Cancelled or Paid out* - ???

## Other questions
* When cancelling a bucket, how do we register the return of funds to the users account?

## Comments
Assuming what I’ve written above is correct I think the conceptual solution makes total sense. Great work!

Implementation wise I think the state model is dangerously unclear in the code and I think it’s high risk going forward. It’s too complex and there’s a lot _illegal_ states and too much redundancy in state representation. I’d definitely prefer to clean that up since we already have our hands in the deep in the mud.

**Comment by chime-mu** [comment]
To be fair though - the complexity in the state model is in no way connected to the work in this ticket - it's just I prefer refactoring code that's hard to understand when I have my fingers in it - as in always leave the place cleaner than I found it.

**Comment by chime-mu** [comment]
Ok, again assuming my understanding is correct, one way to refactor the state model in the code could be:

1. Build a `state` function on the bucket object that returns a `:symbol` designating the state given all the different variables that defines the state. 
2. Replace all instances of code that reads the `status`variable from a bucket with a call to the new `state` function.
3. Replace all instances of the code that checks if a date (`live_at`, `funded_at`, ...) exists (not needing the actual date), with a call to the new `state` function.

Apologies if I'm stating the obvious.

**Comment by jessykate** [comment]
my sense is that refactoring the state model is a separate ticket as there will be a lot of finicky refactoring and testing. since the actual work in this ticket is not too massive, let's push forward with it and then make a separate ticket for the overall state model refactor.

**Comment by jessykate** [comment]
@chime-mu for the structural summary, i actually edited your comment above to add comments inline as i thought it would be easier... jFYI! i clarified how some of the states are represented and how refunds currently work.

**Comment by chime-mu** [comment]
Thanks for the comments and feedback @jessykate :)

I love the documentation of the state model. Very helpful!

As for the suggested `refunded_at`field, yes, we could do that - although that data would be mutually exclusive with the `paid_at` date - so maybe they could be combined as a `closed_at` field? Not very important at this point.

I agree the refactoring of the state model might be excessive - and definitely something we can wait doing as it will make this already pretty big ticket explode.

It's still not clear to me how you will handle to buckets currently archived (which was what I thought was "paid out or cancelled - we don't really know yet"), but as long as it's clear to the two of you, all is well :)

I've to admit to some nervousness on the loss traceability on financial changes (buckets being funded and then cancelled). Especially when we have more users and people start complaining about sudden changes which they don't understand and we can't see what has happened, only guess. In general I like storing sufficient information to be able to know what has happened at any point in time - and even more so with financial information.

That said I completely agree on leaving things as they are now - and I guess this points to a more generic discussion about design principles, which I think would be good to have at some point. I've added a note to the BCN sheet.

**Comment by jlopker** [comment]
@chime-mu do you have some time to QA what i've done? 
https://github.com/cobudget/cobudget-ui/pull/346 
https://github.com/cobudget/cobudget-api/pull/167
