### ISSUE TITLE
Verify that backups work

### ISSUE THREAD

**Issue by Powersource** [cobudget/cobudget#288]
* [ ] Digitalocean server
* [ ] Atlas db (mongodb)

We could probably verify the digitalocean backup by restoring to the server we currently have discourse installed on since we don't use that one

**Comment by aerugo** [comment]
Since we no longer deploy to a server, but to Vercel, the only things that can be backed up are the Postgres database and the images on our image hosting service. We can assume that restoring the database from a dump would work, as this is a standard operation. We will need to figure out what to do for the images, but I feel that is a different issue.
