### ISSUE TITLE
[DEV] Refactors resolvers

### ISSUE THREAD

**Issue by rootux** [cobudget/cobudget#48]
`api/resolvers/index.js` is a 1167 lines of code file.
Instead, we should refactor it to separate resolvers per type so we would have resolvers per type so for example `Dream.js` would contain `DreamResolvers = { Dream: {}, Query: dream:{}, Mutation: {} }`

As we work together on the same source - this separation is needed

**Comment by aerugo** [comment]
@gdpelican, @gustavlrsn, @Powersource - should this issue stay open? Do we want to refactor this at some point or are we okay with a long file?

**Comment by Powersource** [comment]
Yeah I'd be happy if it was refactored, although I haven't thought a lot about how to go about it, but there are a few things we could start with:
* @rootux's idea above sounds good.
* We should probably move auth stuff into helpers that we then combine with, [like realities does](https://github.com/Edgeryders-Participio/realities/blob/e66db8993e638e480c1a06565184903a56658a67/api/src/graphql/resolvers/index.js#L169-L171). If you ctrl-f "You need to be" in dreams you find a lot of duplicated code.
* Maybe follow the pattern in realities and split the more db-intimate stuff into a `../connectors/index.js` file. Might be less easy in dreams since in realities it was done to avoid some of the mess of Cypher, in dreams mongoose has taken care of most of that.

**Comment by gdpelican** [comment]
The event hub has the capability to help with this as well; any 'side effects' of the resolvers (like sending emails, posting to Discourse / Loomio, possibly even writing to the local MongoDB) probably want to go into subscribers to keep that file light.

There's also a heap of duplication in there which wants to go away at some point, so I'd vote for keeping this one open.

**Comment by aerugo** [comment]
Closing this in a general issue clean-up. Might reopen again later. 
@gustavlrsn - did anything happen with this in the current big refactoring?

**Comment by Powersource** [comment]
The file seems to be 3002 lines now in the new branch so I'd say this is still very needed.

**Comment by aerugo** [comment]
@alinauroz has started working on this now
