### ISSUE TITLE
Enable the user to toggle which notification emails they get

### ISSUE THREAD

**Issue by Powersource** [cobudget/cobudget#491]
Followup from https://github.com/cobudget/cobudget/issues/393

**Comment by tomomiq** [comment]
hi @Powersource 

Passing back copy revisions and re-ordering: 
￼
<img width="751" alt="Screenshot 2022-03-01 at 15 05 44" src="https://user-images.githubusercontent.com/1287179/156183926-72c68948-52cd-4433-9013-a4381b1cac09.png">

Text ver: 

* I receive funds (to spend on buckets)
* I have been refunded (because a bucket was cancelled)
* Funds have been contributed to my bucket
* There are comments on my bucket
* I am mentioned in a comment
* A new bucket is published
* A bucket I have commented on receives a new comment

**Comment by tomomiq** [comment]
fyi that we checked that emails don't get sent out for each of these notifications when the toggle is OFF

**Comment by Powersource** [comment]
copy and order fixed

**Comment by tomomiq** [comment]
LGTM!
