### ISSUE TITLE
User gets an email notification when admin gives or changes an allocation.

### ISSUE THREAD

**Issue by derekrazo** [cobudget/cobudget#51]
Needs design of the email notifications.

**Comment by jonlemmon** [comment]
Shall we put this on hold in favor of: https://github.com/open-app/cobudget/issues/71.

The difference being that we email the users right before the beginning of a round, instead of when the admin changes their allocation. Emailing before a round might mean we send less emails (which I think would be a good thing).

**Comment by derekrazo** [comment]
+1 to putting this off for #71 

One thing to consider - if the email is about to be sent, and the person has already been given an allocation, the email could still go out with the allocation amount. :)

**Comment by jonlemmon** [comment]
Yep, that's what I imagined. :) my only fear is if putting dollar figures in emails will make them get filtered to spam, but that may be an irrational fear.
