### ISSUE TITLE
Allocating funds to users takes a long time, look at optimizing email notification sending

### ISSUE THREAD

**Issue by Powersource** [cobudget/cobudget#736]
One allocation in production seems to take around 400ms which is way too slow. The slowest call we do in the allocation is probably the email notification that we send.

**Comment by Powersource** [comment]
Trying out just parallelizing it https://github.com/cobudget/cobudget/commit/c2b42ce02f0d2c26367b97786697d3c35601d64f

**Comment by Powersource** [comment]
I think we might need a message queue eventually, once we want stuff like "send out a welcome email in a week". And it might help here as well. A basic tier managed redis on digitalocean is 15$/month, and then on top of that you can run something like https://github.com/redis/node-redis or https://github.com/taskforcesh/bullmq (just ran into these, would have to research more(hmm not sure if those work with serverless)).

**Comment by gustavlrsn** [comment]
> I think we might need a message queue eventually, once we want stuff like "send out a welcome email in a week". And it might help here as well. A basic tier managed redis on digitalocean is 15$/month, and then on top of that you can run something like https://github.com/redis/node-redis or https://github.com/taskforcesh/bullmq (just ran into these, would have to research more(hmm not sure if those work with serverless)).

Wouldn't this be pretty overcomplicated at this point? Postmark is basically our message queue. We should just make sure to use it properly and not like I did when allocating to the entire members array and awaiting the responses iteratively 😅

Let's think about scheduled emails when we need it.

There are many ways we could improve further upon the fix you implemented (which already seems to be enough)

One thing is to do email sending as a batch request https://postmarkapp.com/developer/api/email-api#send-batch-emails

Another would be to simply not await the postmark request, since we are not doing anything with the response anyhow.

**Comment by Powersource** [comment]
I was considering this for if postmark couldn't handle us `post`ing too many emails at the same time and we needed to space it out. But if they seem to be able to handle it then let's keep how it is now.

We don't need the response but we want the request to have reached postmark before our serverless function gets shut off, so I think awaiting might still be good?

Yeah batch requesting would be a good next step. I think we might be able to keep that refactor contained in the email sending file/a new postmark singleton we create instead of having to send batches in e.g. the resolver file, by using a debounce function.

**Comment by aerugo** [comment]
Do we
