### ISSUE TITLE
[Discussion] Remove budget overview feature

### ISSUE THREAD

**Issue by jonlemmon** [cobudget/cobudget#82]

**Comment by jonlemmon** [comment]
Hey all, I'd like to discuss removing the "Budget Overview" feature from Cobudget. I know that our groups use it currently, however I think it's something that could easily be done outside of cobudget (e.g. in the email or Loomio that goes out before hand).

It's getting in the way for me when I'm trying to design the "admin starts round" feature, since we default to the overview page. And every feature that we have means we have more things to maintain and less energy to put into other features.

I'd like to strongly suggest removing this feature unless anyone can come up with a very good reason not to.

**Comment by ahdinosaur** [comment]
> And every feature that we have means we have more things to maintain and less energy to put into other features.

:+1:

i could go either way on whether or not this feature is worth the cost, so i abstain.

**Comment by getresults** [comment]
From the user side I find the budget overview valuable.  It provides an additional set of checks & balances to confirm that allocations have been entered correctly.  It provides a historical summary of budgets in past rounds to cobudget users.   

Enspiral is discussing removing cobudget announcements from loomio due to excessive noise with multiple rounds each month and moving to email only to people with allocations.  If we end up relying on emails to summarise budgets it becomes so much more difficult for users to look back and see what's been happening - instead organisation budgeting becomes fragmented over different platforms. 

I would like to see it stay but I'm happy to explore ways of changing to make it easier on the development side.  While I'm guessing it won't make any real difference, I'm not the least bit concerned about whether the budget overview is the default page.  

I'd be very interested to hear feedback from other end users - perhaps open up as a discussion in the cobudget loomio group?

**Comment by jonlemmon** [comment]
Thanks for the feedback Phill.

How does it confirm that allocations have been entered correctly?

I can see that it provides a history of the budget, but if each round has a
short description with a link to a spreadsheet containing additional budget
data would that accomplish the same thing?

Cool to hear that you don't mind if it's the default page. In that case I
think a good start would be to make buckets the main page and rename
"Overview" to "Budget Details" and put it as the furthest item on the right
in the round menu bar. Then we can do some more investigation about the
usefulness of that feature.

Good idea to open this up as a discussion on Loomio as well...

**Comment by getresults** [comment]
Hey Jon, 

For Enspiral when entering allocations I can do a quick check that the figure I entered for allocations in the budget matches the total allocations entered before the round.  Yes, I can compare against the same figure in the spreadsheet but it's nice to have it in the same app. 

We could have a link back to a spreadsheet but that makes an assumption that all organisations are using Google Apps or similar, right?   

Also, having the budget summary in an online spreadsheet opens up the possibility of people (intentionally or unintentionally) editing spreadsheets for past budgeting rounds if permissions aren't locked.  

One nice thing about having a summary in cobudget is that they are locked and always available for historical review in a single location. 

It might also be worth considering whether organisations have record keeping policies that would require budget breakdowns to be stored with allocation decisions? 

I know I'm expressing some personal bias here :)  I'm also trying to look at it from both an end user point of view (I have an allocation but how does it fit into the larger budget picture?) and an organisation admin point of view (what information about budgets will I need to look up and report back on in future?).

Totally cool with moving Budget Details to the last tab.

**Comment by derekrazo** [comment]
Pretty close to a block on this one for me.

We've had no complaints or any indication from users that this feature gets in their way. As far as I can tell we have no user-driven reason for getting rid of this feature. Feedback has been that users would like MORE in the budget overview, certainly not less and certainly not getting rid of it. 

I'd say this is a good case of "we're not all talking to the users" blindsight. Red vic used this quite successfully. 

The idea of removing a useful feature because it's getting in the way of designing a new feature is quite strange to me. Maybe you could be more specific of how it's getting in the way?

The argument of the overview being a difficult to maintain feature seems quite thin to me.
